language: node_js
node_js:
- 6
- 8
matrix:
  fast_finish: true
notifications:
  slack:
    secure: jAz9NlQaKUjvEq3XjEJqiji2iLUNxvDkJe6mq1omug92RurkJ0/NTBeisSCT+WOAsNAT7eAuSfDDiBAySIwKXH2adKeY1p084vW58puurmZiA/fAji29axziJi0hn83tXv5oOKT1mey8RwOi02ENxn1kfixOb0dc8YaTrPRfR9DDo44OACfiKJ1C0LVFe1Sp1uHCps3MqlWtEg6indekCqOYCqc6iLGLnZhLJXx1CcBcgU59gof0PbFc4w9VNPeIS5eT+Ik52qhV3MXC2p792vv+nzHP40sGspIiRPro5+C2M4iKBxmEkK7mnStYpKeqMjZLF7H90UmsBSBLWr/GbbmA6RHwvPsJPUfIa2BJoJDpojUpzGztAt3VA2sqqy6kf0MUMJWSUAVU2tzkaFUdJyYwV5Ly4XSASEcK/Zjt8PXTQWUFrtJyMQhH0PRuQ1DXdMZ8+Tcv0K8bmZEtDmOTCPhYY4FqfywUJZQdImMnXrnGNKClAnm+ibrreFVPIs0a9Q071fgvnSOMec362pnew9SstKiwvZADM0aTvU5bKj1Pa7AJ6JbSAnyq3VTqvDWTRzkCS7nBKEdNhkIwsD63/atNYZfRM9//V3gh6zaOa+yrYxNez4iBRQX52xKHDAptnPEePVi8pI/9IWVTDgw+SFKW5NDRxRNF6sZO40P2+js=
cache:
  yarn: true
